name: algo commit autocheck

on:
  schedule:
    - cron: '0 0 * * 2-6'

  workflow_dispatch:

jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - name: check commit 
        run: |
          ls -al
          count=$(cat users.json | jq '. | length')
          for ((i = 0; i < count; i++)); do
            repo=$(cat users.json | jq -r ".[$i].repo")
            echo $repo
            curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN_GITHUB }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo/commits
          done