name: algo commit autocheck

on:
  schedule:
    - cron: '0 0 * * 2-6'

  workflow_dispatch:

jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.TOKEN_GITHUB }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/daily-problem-solving/252/commits