name: algo commit autocheck

on:
  schedule:
    - cron: '0 15 * * 1-5'

  workflow_dispatch:

jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: check commit 
        run: |
          count=$(cat users.json | jq '. | length')
          date -u -I >> temp.txt
          for ((i = 0; i < count; i++)); do
            cat users.json | jq -r ".[$i].name" >> temp.txt
            repo=$(cat users.json | jq -r ".[$i].repo")

            latest_date=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN_GITHUB }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo/commits | jq -r ".[0].commit.committer.date")
            
            latest_date_epoch=$(date -d "$latest_date" +%s)
            start_date_epoch=$(date -d "yesterday 15:00" +%s)
            end_date_epoch=$(date -d "today 15:00" +%s)

            if [[ $latest_date_epoch -ge $start_date_epoch && $latest_date_epoch -le $end_date_epoch ]]; then
              echo "Y" >> temp.txt
            else
              echo "N" >> temp.txt
            fi
          done

          cat temp.txt >> README.md
          echo "<br>" >> README.md
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}