name: algo commit autocheck

on:
  schedule:
    - cron: '0 0 * * 2-6'

  workflow_dispatch:

jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit
        run: |
          ls -al
          sudo chmod +x scripts/check.sh
          ./scripts/check.sh