name: algo commit autocheck

on:
  schedule:
    - cron: '0 15 * * 1-5'

  workflow_dispatch:

permissions: write-all

jobs:
  check-commit:
    if: github.repository == 'daily-problem-solving/algo-commit-autocheck'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: check commit 
        run: |
          count=$(cat users.json | jq '. | length')

          date_value=$(date -u -I)
          check_list=()

          for ((i = 0; i < count; i++)); do
            repo=$(cat users.json | jq -r ".[$i].repo")

            latest_date=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN_GITHUB }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo/commits | jq -r ".[0].commit.committer.date")
            
            latest_date_epoch=$(date -d "$latest_date" +%s)
            start_date_epoch=$(date -d "yesterday 15:00" +%s)
            end_date_epoch=$(date -d "today 15:00" +%s)

            if [[ $latest_date_epoch -ge $start_date_epoch && $latest_date_epoch -le $end_date_epoch ]]; then
              check_list[i]="Y"
            else
              check_list[i]="N"
            fi
          done

          printf "|%s|%s|%s|%s|\n" "`echo "$date_value"`" "${check_list[0]}" "${check_list[1]}" "${check_list[2]}" >> README.md

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}